/* Generated by JSIL v0.8.2 build 30747. See http://jsil.org/ for more information. */ 
'use strict';
var $asm_Application1 = JSIL.DeclareAssembly("Application1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

/* class ??Application1??Component??App??Xaml??Factory */ 

(function $1c0$1c0Application1$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.TypeInstantiationHelper)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_Application1.Application1.App)) ();
  };

  function $1c0$1c0Application1$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory_Instantiate () {
    return $T00()['Instantiate']($T01().__Type__);
  };

  JSIL.MakeStaticClass("\u01c0\u01c0Application1\u01c0\u01c0Component\u01c0\u01c0App\u01c0\u01c0Xaml\u01c0\u01c0Factory", true, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:true , Public:true }, "Instantiate", 
      JSIL.MethodSignature.Return($.Object), 
      $1c0$1c0Application1$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory_Instantiate
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class ??Application1??Component??Mainpage??Xaml??Factory */ 

(function $1c0$1c0Application1$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.TypeInstantiationHelper)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_Application1.Application1.MainPage)) ();
  };

  function $1c0$1c0Application1$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory_Instantiate () {
    return $T00()['Instantiate']($T01().__Type__);
  };

  JSIL.MakeStaticClass("\u01c0\u01c0Application1\u01c0\u01c0Component\u01c0\u01c0Mainpage\u01c0\u01c0Xaml\u01c0\u01c0Factory", true, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:true , Public:true }, "Instantiate", 
      JSIL.MethodSignature.Return($.Object), 
      $1c0$1c0Application1$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory_Instantiate
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

JSIL.DeclareNamespace("Application1");
/* class Application1.App */ 

(function App$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Application)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_Application1.Application1.MainPage)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Window)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.StartupAssemblyInfo)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.ResourceDictionary)) ();
  };

  function App__ctor () {
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    var content = new ($T01())();
    $T02().Window$Current$value['set_Content'](content);
  };

  function App_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      if (false) {
        $T03().$Cast(this).XamlSourcePath = "Application1\\App.xaml";
      }
      $T04().OutputRootPath = "Output\\";
      $T04().OutputAppFilesPath = "app-cshtml5\\app\\";
      $T04().OutputLibrariesPath = "app-cshtml5\\libs\\";
      $T04().OutputResourcesPath = "app-cshtml5\\res\\";
      var resources = new ($T05())();
      this['set_Resources'](resources);
      this['set_Resources'](resources);
    }
  };

  JSIL.MakeType({
      BaseType: $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Application"), 
      Name: "Application1.App", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      App__ctor
    );

    $.Method({Static:false, Public:true }, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      App_InitializeComponent
    );

    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class Application1.CItem */ 

(function CItem$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };

  function CItem__ctor () {
  };

  function CItem_get_Option () {
    return this.CItem$Option$value;
  };

  function CItem_get_Value () {
    return this.CItem$Value$value;
  };

  function CItem_set_Option (value) {
    this.CItem$Option$value = value;
  };

  function CItem_set_Value (value) {
    this.CItem$Value$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm_mscorlib.TypeRef("System.Object"), 
      Name: "Application1.CItem", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      CItem__ctor
    );

    $.Method({Static:false, Public:true }, "get_Option", 
      JSIL.MethodSignature.Return($.String), 
      CItem_get_Option
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Value", 
      JSIL.MethodSignature.Return($.String), 
      CItem_get_Value
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Option", 
      JSIL.MethodSignature.Action($.String), 
      CItem_set_Option
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Value", 
      JSIL.MethodSignature.Action($.String), 
      CItem_set_Value
    )
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "CItem$Value$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"))
      .Attribute($asm_mscorlib.TypeRef("System.Diagnostics.DebuggerBrowsableAttribute"), function () { return [$asm_mscorlib.System.Diagnostics.DebuggerBrowsableState.Never]; }); 
    $['Field']({Static:false, Public:false}, "CItem$Option$value", $.String)
      .Attribute($asm_mscorlib.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"))
      .Attribute($asm_mscorlib.TypeRef("System.Diagnostics.DebuggerBrowsableAttribute"), function () { return [$asm_mscorlib.System.Diagnostics.DebuggerBrowsableState.Never]; }); 
    $.Property({Static:false, Public:true }, "Value", $.String);

    $.Property({Static:false, Public:true }, "Option", $.String);

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class Application1.MainPage */ 

(function MainPage$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_mscorlib.System.Collections.Generic.List$b1.Of($asm_Application1.Application1.CItem))) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Page)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_CSharpXamlForHtml5_System_dll.System.Net.WebClient)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm_mscorlib.System.Text.Encoding)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm_CSharpXamlForHtml5_System_dll.System.Net.WebHeaderCollection)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm_mscorlib.System.String)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm_mscorlib.System.Int32)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm_mscorlib.System.Char)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm_mscorlib.System.Boolean)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm_mscorlib.System.Int64)) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm_mscorlib.System.Convert)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm_Application1.Application1.CItem)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.TextBox)) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm_mscorlib.System.Object)) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs)) ();
  };
  var $T0F = function () {
    return ($T0F = JSIL.Memoize($asm_mscorlib.System.Exception)) ();
  };
  var $T10 = function () {
    return ($T10 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Primitives.Selector)) ();
  };
  var $T11 = function () {
    return ($T11 = JSIL.Memoize($asm_mscorlib.System.Math)) ();
  };
  var $T12 = function () {
    return ($T12 = JSIL.Memoize($asm_mscorlib.System.Double)) ();
  };
  var $T13 = function () {
    return ($T13 = JSIL.Memoize($asm_mscorlib.System.FormatException)) ();
  };
  var $T14 = function () {
    return ($T14 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.MessageBox)) ();
  };
  var $T15 = function () {
    return ($T15 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ContentControl)) ();
  };
  var $T16 = function () {
    return ($T16 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement)) ();
  };
  var $T17 = function () {
    return ($T17 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Grid)) ();
  };
  var $T18 = function () {
    return ($T18 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.TabControl)) ();
  };
  var $T19 = function () {
    return ($T19 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.TabItem)) ();
  };
  var $T1A = function () {
    return ($T1A = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Control)) ();
  };
  var $T1B = function () {
    return ($T1B = JSIL.Memoize($asm_CSharpXamlForHtml5.DotNetForHtml5.Core.TypeFromStringConverters)) ();
  };
  var $T1C = function () {
    return ($T1C = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.RowDefinition)) ();
  };
  var $T1D = function () {
    return ($T1D = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.GridLength)) ();
  };
  var $T1E = function () {
    return ($T1E = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.RowDefinition))) ();
  };
  var $T1F = function () {
    return ($T1F = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Border)) ();
  };
  var $T20 = function () {
    return ($T20 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Media.Brush)) ();
  };
  var $T21 = function () {
    return ($T21 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Thickness)) ();
  };
  var $T22 = function () {
    return ($T22 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.FrameworkElement)) ();
  };
  var $T23 = function () {
    return ($T23 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.VerticalAlignment)) ();
  };
  var $T24 = function () {
    return ($T24 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.TextBlock)) ();
  };
  var $T25 = function () {
    return ($T25 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Text.FontWeight)) ();
  };
  var $T26 = function () {
    return ($T26 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ColumnDefinition)) ();
  };
  var $T27 = function () {
    return ($T27 = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ColumnDefinition))) ();
  };
  var $T28 = function () {
    return ($T28 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ComboBox)) ();
  };
  var $T29 = function () {
    return ($T29 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.UserControl)) ();
  };
  var $T2A = function () {
    return ($T2A = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ItemsControl)) ();
  };
  var $T2B = function () {
    return ($T2B = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Data.Binding)) ();
  };
  var $T2C = function () {
    return ($T2C = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.PropertyPath)) ();
  };
  var $T2D = function () {
    return ($T2D = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.HorizontalAlignment)) ();
  };
  var $T2E = function () {
    return ($T2E = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement))) ();
  };
  var $T2F = function () {
    return ($T2F = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Panel)) ();
  };
  var $T30 = function () {
    return ($T30 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Button)) ();
  };
  var $T31 = function () {
    return ($T31 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Primitives.ButtonBase)) ();
  };
  var $T32 = function () {
    return ($T32 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventHandler)) ();
  };
  var $T33 = function () {
    return ($T33 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Label)) ();
  };
  var $T34 = function () {
    return ($T34 = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_mscorlib.System.Object))) ();
  };
  var $T35 = function () {
    return ($T35 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Data.RelativeSource)) ();
  };
  var $T36 = function () {
    return ($T36 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Data.RelativeSourceMode)) ();
  };
  var $T37 = function () {
    return ($T37 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.DependencyObject)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm_mscorlib.TypeRef("System.Collections.Generic.List`1", [$asm_Application1.TypeRef("Application1.CItem")]), null))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm_mscorlib.TypeRef("System.String"), $asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(new JSIL.MethodSignature($asm_mscorlib.TypeRef("System.String"), [$asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S03 = function () {
    return ($S03 = JSIL.Memoize(new JSIL.MethodSignature($asm_mscorlib.TypeRef("System.Int32"), [$asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S04 = function () {
    return ($S04 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm_Application1.TypeRef("Application1.CItem")]))) ();
  };
  var $S05 = function () {
    return ($S05 = JSIL.Memoize(new JSIL.ConstructorSignature($asm_mscorlib.TypeRef("System.Exception"), [$asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S06 = function () {
    return ($S06 = JSIL.Memoize(new JSIL.MethodSignature($asm_mscorlib.TypeRef("System.Int32"), [$asm_mscorlib.TypeRef("System.Double")]))) ();
  };
  var $S07 = function () {
    return ($S07 = JSIL.Memoize(new JSIL.MethodSignature($asm_mscorlib.TypeRef("System.Int64"), [$asm_mscorlib.TypeRef("System.String")]))) ();
  };
  var $S08 = function () {
    return ($S08 = JSIL.Memoize(new JSIL.ConstructorSignature($asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Data.Binding"), null))) ();
  };
  var $S09 = function () {
    return ($S09 = JSIL.Memoize(new JSIL.ConstructorSignature($asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Data.RelativeSource"), null))) ();
  };

  function MainPage__ctor () {
    this.Items = $S00().Construct();
    $T01().prototype['_ctor'].call(this);
    var webClient = new ($T02())();
    webClient.WebClient$Encoding$value = $T03()['get_UTF8']();
    $S01().CallVirtual("Add", null, webClient['get_Headers'](), "origin", "dcinside.com");
    var text = $S02().CallVirtual("DownloadString", null, webClient, "http://alloworigincors.herokuapp.com/http://gall.dcinside.com/mgallery/board/view/?id=toramonline&no=26051&page=1");
    text = this['CutString'](text, "<div class=\"writing_view_box\">", "Data_End");

    for (text = this['CutString'](text, "<p>", "<p>"); (text.indexOf("<span style")) !== -1; text = (System.String.Remove(text, text.indexOf("<span style"), 35))) {
    }

    for (text = (text.substr(0, text.indexOf("Data_End"))); (text.indexOf("</span></p><p>")) !== -1; text = (System.String.Remove(text, text.indexOf("</span></p><p>"), 14))) {
      text = (System.String.Insert(text, text.indexOf("</span></p><p>"), "&"));
    }
    var num = 0;

  $loop2: 
    for (var i = 0; i < (text.lastIndexOf("&")); ) {
      var flag = ((text[i])['charCodeAt'](0) | 0) === (("#")['charCodeAt'](0) | 0);
      if (flag) {

        for (i = ((i + 1) | 0); ((text[i])['charCodeAt'](0) | 0) !== (("&")['charCodeAt'](0) | 0); i = ((i + 1) | 0)) {
          num = ((((Math.imul(num, 10) + ((text[i])['charCodeAt'](0) | 0)) | 0) - 48) | 0);
        }
        break $loop2;
      }
      var num2 = $T09()['Create'](0, 0, 0);
      var text2 = "";

      while (((text[i])['charCodeAt'](0) | 0) !== (("=")['charCodeAt'](0) | 0)) {
        num2 = $T09()['op_Addition'](
          $T09()['op_Multiplication'](num2, $T09()['Create'](10, 0, 0)), 
          $T09()['FromNumber']($S03().CallStatic($T0A(), "ToInt32", null, (text[i])['toString']()))
        );
        i = ((i + 1) | 0);
      }

      for (i = ((i + 1) | 0); ((text[i])['charCodeAt'](0) | 0) !== (("&")['charCodeAt'](0) | 0); i = ((i + 1) | 0)) {
        text2 = (JSIL.ConcatString(text2, (text[i])['toString']()));
      }
      i = ((i + 1) | 0);
      var expr_1E2 = new ($T0B())();
      expr_1E2.CItem$Value$value = ((num2).toString());
      expr_1E2.CItem$Option$value = text2;
      $S04().CallVirtual("Add", null, this.Items, expr_1E2);
    }
    this['InitializeComponent']();
    (this.AStartLVval)['set_Text'](this.ADestLVval.Text = this.BStartLVval.Text = this.CDestLVval.Text = "0");
    (this.AStartLevel)['set_Text'](this.BStartLevel.Text = "1");
    (this.ADestLevel)['set_Text'](this.CDestLevel.Text = ((num).toString()));
  };

  function MainPage_AConfirm (sender, e, $exception) {
    var num3 = $T09()['Create'](0, 0, 0);
    var num = $T09()['Create'](0, 0, 0);
    var num2 = num3 = $T09()['Create'](0, 0, 0);
    var num4 = ((this.ADestMqBox)['get_SelectedIndex']() | 0);
    var num5 = $T09()['Create'](0, 0, 0);
    try {
      var num6 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.AStartLevel)['get_Text']()) | 0);
      var num7 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.AStartLVval)['get_Text']()) | 0);
      if ((num6 <= 0) || 
        (num6 > 500) || 
        (num7 < 0) || (num7 >= 100)) {
        throw $S05().Construct("\uc720\ud6a8\ud55c \uac12\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694");
      }

      for (var i = 1; i < num6; i = ((i + 1) | 0)) {
        num3 = $T09()['op_Addition'](num3, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+i, 4)) / 40)) + +(i * 2))));
      }
      num3 = $T09()['op_Addition'](num3, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +((((+(((Math.pow(+num6, 4)) / 40)) + +(num6 * 2)) * +num7) / 100)))));
      var num8 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.ADestLevel)['get_Text']()) | 0);
      var num9 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.ADestLVval)['get_Text']()) | 0);
      if ((num8 <= 0) || 
        (num8 > 500) || 
        (num9 < 0) || (num9 >= 100)) {
        throw $S05().Construct("\uc720\ud6a8\ud55c \uac12\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694");
      }

      for (var j = 1; j < num8; j = ((j + 1) | 0)) {
        num2 = $T09()['op_Addition'](num2, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+j, 4)) / 40)) + +(j * 2))));
      }
      num2 = $T09()['op_Addition'](num2, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +((((+(((Math.pow(+num8, 4)) / 40)) + +(num8 * 2)) * +num9) / 100)))));
      var flag3 = $T09()['op_GreaterThanOrEqual'](num3, num2);
      if (flag3) {
        throw $S05().Construct("\uc2dc\uc791\ub808\ubca8\uc758 EXP\uac12\uc740 \ubaa9\ud45c\ub808\ubca8\uc758 EXP\uac12\ubcf4\ub2e4 \ud06c\uac70\ub098 \uac19\uc744\uc218 \uc5c6\uc2b5\ub2c8\ub2e4");
      }
      var flag4 = ((this.ADestMqBox)['get_SelectedIndex']() | 0) === 1;
      if (flag4) {
        throw $S05().Construct(("\"" + (this.Items)['get_Item'](1).CItem$Option$value + "\"\uc740\n\uba54\uc778 \uc2dc\ub098\ub9ac\uc624\uc758 \uc885\ucc29\uc810\uc774 \ub420 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4"));
      }
    } catch ($exception) {
      if ($T13().$Is($exception)) {
        $T14()['Show']("\uc815\uc218\ub9cc \uc785\ub825\ud574\uc8fc\uc138\uc694");
        return;
      } else {
        $T14()['Show']($exception['get_Message']());
        return;
      }
    }

    for (var k = 1; k <= num4; k = ((k + 1) | 0)) {
      num5 = $T09()['op_Addition'](num5, $T09()['FromNumber']($S03().CallStatic($T0A(), "ToInt32", null, (this.Items)['get_Item'](k).CItem$Value$value)));
    }
    var num10 = $T09()['Create'](1, 0, 0);
    var flag5 = $T09()['op_LessThanOrEqual']($T09()['op_Subtraction'](num2, num3), num5);
    if (flag5) {

      while ($T09()['op_GreaterThan']($T09()['op_Subtraction'](num2, num3), num)) {
        num = $T09()['op_Addition'](num, $S07().CallStatic($T0A(), "ToInt64", null, (this.Items)['get_Item'](num4).CItem$Value$value));
        num4 = ((num4 - 1) | 0);
      }
    } else {
      var num11 = $T09()['op_Subtraction'](num2, num3);
      var num12 = num5;

      while ($T09()['op_GreaterThan'](num11, num5)) {
        num5 = $T09()['op_Addition'](num5, num12);
        num10 = $T09()['op_Addition'](num10, $T09()['Create'](1, 0, 0));
      }

      while ($T09()['op_GreaterThan'](num11, num)) {
        num = $T09()['op_Addition'](num, $T09()['op_Multiplication'](num10, $S07().CallStatic($T0A(), "ToInt64", null, (this.Items)['get_Item'](num4).CItem$Value$value)));
        num4 = ((num4 - 1) | 0);
      }
    }
    (this.AResultWindow)['set_Content'](($T05()['Format']("\ubaa8\ud5d8\uac00\uc758 \uc77c\uae30\ub294 {0}\uac1c \ud544\uc694\ud558\uba70\n", num10) + "\"" + (this.Items)['get_Item'](((num4 + 1) | 0)).CItem$Option$value + "\"\ubd80\ud130\n\uc2dc\ub098\ub9ac\uc624\ub97c \uc2dc\uc791\ud574\uc57c \ubaa9\ud45c\ub808\ubca8\uc5d0 \ub3c4\ub2ec\ud569\ub2c8\ub2e4"));
  };

  function MainPage_BConfirm (sender, e, $exception) {
    var num = $T09()['Create'](0, 0, 0);
    var num2 = $T09()['Create'](0, 0, 0);
    try {
      var num3 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.BStartLevel)['get_Text']()) | 0);
      var num4 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.BStartLVval)['get_Text']()) | 0);
      if ((num3 <= 0) || 
        (num3 > 500) || 
        (num4 < 0) || (num4 >= 100)) {
        throw $S05().Construct("\uc720\ud6a8\ud55c \uac12\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694");
      }

      for (var i = 1; i < num3; i = ((i + 1) | 0)) {
        num = $T09()['op_Addition'](num, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+i, 4)) / 40)) + +(i * 2))));
      }
      num = $T09()['op_Addition'](num, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +((((+(((Math.pow(+num3, 4)) / 40)) + +(num3 * 2)) * +num4) / 100)))));
      var flag2 = ((this.BStartMqBox)['get_SelectedIndex']() | 0) >= ((this.BDestMqBox)['get_SelectedIndex']() | 0);
      if (flag2) {
        throw $S05().Construct("\uc2dc\ub098\ub9ac\uc624 \uc2dc\uc791\uc810\uc774 \uc2dc\ub098\ub9ac\uc624 \uc885\ucc29\uc810 \uc774\ud6c4\uc77c\uc218 \uc5c6\uc2b5\ub2c8\ub2e4");
      }
    } catch ($exception) {
      if ($T13().$Is($exception)) {
        $T14()['Show']("\uc815\uc218\ub9cc \uc785\ub825\ud574\uc8fc\uc138\uc694");
        return;
      } else {
        $T14()['Show']($exception['get_Message']());
        return;
      }
    }
    var j = ((this.BStartMqBox)['get_SelectedIndex']() | 0);
    var selectedIndex = ((this.BDestMqBox)['get_SelectedIndex']() | 0);

    while (j <= selectedIndex) {
      num2 = $T09()['op_Addition'](num2, $T09()['FromNumber']($S03().CallStatic($T0A(), "ToInt32", null, (this.Items)['get_Item'](j).CItem$Value$value)));
      j = ((j + 1) | 0);
    }
    num = $T09()['op_Addition'](num, num2);
    var num5 = 1;
    var num6 = $T09()['Create'](0, 0, 0);

    while ($T09()['op_GreaterThan'](num, num6)) {
      num6 = $T09()['op_Addition'](num6, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+num5, 4)) / 40)) + +(num5 * 2))));
      num5 = ((num5 + 1) | 0);
    }
    num5 = ((num5 - 1) | 0);
    num6 = $T09()['op_Subtraction'](num6, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+num5, 4)) / 40)) + +(num5 * 2))));
    (this.BResultWindow)['set_Content'](JSIL.ConcatString($T05()['Format']("{0} ({1}%) \uc5d0 \ub3c4\ub2ec\ud569\ub2c8\ub2e4\n", num5, Math.floor(+((+($T09()['op_Multiplication'](
              $T09()['Create'](100, 0, 0), 
              $T09()['op_Subtraction'](num, num6)
            ))['ToNumber'](-1, false) / (+(((Math.pow(+num5, 4)) / 40)) + +(num5 * 2)))))), "(\uc624\ucc28\ubc94\uc704 \xb11% \uc874\uc7ac\uac00\ub2a5)"));
  };

  function MainPage_CConfirm (sender, e, $exception) {
    var num = $T09()['Create'](0, 0, 0);
    var num2 = $T09()['Create'](0, 0, 0);
    try {
      var num3 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.CDestLevel)['get_Text']()) | 0);
      var num4 = ($S03().CallStatic($T0A(), "ToInt32", null, (this.CDestLVval)['get_Text']()) | 0);
      if ((num3 <= 0) || 
        (num3 > 500) || 
        (num4 < 0) || (num4 >= 100)) {
        throw $S05().Construct("\uc720\ud6a8\ud55c \uac12\uc744 \uc785\ub825\ud574\uc8fc\uc138\uc694");
      }

      for (var i = 1; i < num3; i = ((i + 1) | 0)) {
        num = $T09()['op_Addition'](num, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+i, 4)) / 40)) + +(i * 2))));
      }
      num = $T09()['op_Addition'](num, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +((((+(((Math.pow(+num3, 4)) / 40)) + +(num3 * 2)) * +num4) / 100)))));
      var flag2 = ((this.CStartMqBox)['get_SelectedIndex']() | 0) >= ((this.CDestMqBox)['get_SelectedIndex']() | 0);
      if (flag2) {
        throw $S05().Construct("\uc2dc\ub098\ub9ac\uc624 \uc2dc\uc791\uc810\uc774 \uc2dc\ub098\ub9ac\uc624 \uc885\ucc29\uc810 \uc774\ud6c4\uc77c\uc218 \uc5c6\uc2b5\ub2c8\ub2e4");
      }
    } catch ($exception) {
      if ($T13().$Is($exception)) {
        $T14()['Show']("\uc815\uc218\ub9cc \uc785\ub825\ud574\uc8fc\uc138\uc694");
        return;
      } else {
        $T14()['Show']($exception['get_Message']());
        return;
      }
    }
    var j = ((this.CStartMqBox)['get_SelectedIndex']() | 0);
    var selectedIndex = ((this.CDestMqBox)['get_SelectedIndex']() | 0);

    while (j <= selectedIndex) {
      num2 = $T09()['op_Addition'](num2, $T09()['FromNumber']($S03().CallStatic($T0A(), "ToInt32", null, (this.Items)['get_Item'](j).CItem$Value$value)));
      j = ((j + 1) | 0);
    }
    var num5 = $T09()['op_Subtraction'](num, num2);
    if ($T09()['op_GreaterThan'](num5, $T09()['Create'](0, 0, 0))) {
      var num6 = 1;
      var num7 = $T09()['Create'](0, 0, 0);

      while ($T09()['op_GreaterThan'](num5, num7)) {
        num7 = $T09()['op_Addition'](num7, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+num6, 4)) / 40)) + +(num6 * 2))));
        num6 = ((num6 + 1) | 0);
      }
      num6 = ((num6 - 1) | 0);
      num7 = $T09()['op_Subtraction'](num7, $T09()['FromNumber']($S06().CallStatic($T0A(), "ToInt32", null, +(((Math.pow(+num6, 4)) / 40)) + +(num6 * 2))));
      (this.CResultWindow)['set_Content'](JSIL.ConcatString($T05()['Format']("{0} ({1}%) \uc5d0\uc11c \uc2dc\uc791\ud574\uc57c\ud569\ub2c8\ub2e4\n", num6, Math.floor(+((+($T09()['op_Multiplication'](
                $T09()['Create'](100, 0, 0), 
                $T09()['op_Subtraction'](num5, num7)
              ))['ToNumber'](-1, false) / (+(((Math.pow(+num6, 4)) / 40)) + +(num6 * 2)))))), "(\uc624\ucc28\ubc94\uc704 \xb11% \uc874\uc7ac\uac00\ub2a5)"));
    } else {
      (this.CResultWindow)['set_Content']("1 (0%) \uc5d0\uc11c \uc2dc\uc791\ud574\uc57c\ud569\ub2c8\ub2e4\n(\uc624\ucc28\ubc94\uc704 \xb11% \uc874\uc7ac\uac00\ub2a5)");
    }
  };

  function MainPage_CutString (data, start, end) {
    var flag = ((data.indexOf(start)) === -1) || 
    ((data.lastIndexOf(end)) === -1);
    if (flag) {
      var result = data;
    } else {
      result = (data.substr((((data.indexOf(start)) + (start.length | 0)) | 0), data.lastIndexOf(end)));
    }
    return result;
  };

  function MainPage_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      if (this !== null) {
        $T16().$Cast(this).XamlSourcePath = "Application1\\MainPage.xaml";
      }
      var grid = new ($T17())();
      var tabControl = new ($T18())();
      var tabItem = new ($T19())();
      tabItem['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "13")));
      tabItem['set_Header']($T1B()['ConvertFromInvariantString']($T0D().__Type__, "\uc2dc\ub098\ub9ac\uc624 \uc2dc\uc791\uc704\uce58 \uacc4\uc0b0"));
      var grid2 = new ($T17())();
      var rowDefinition = new ($T1C())();
      (rowDefinition.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition2 = new ($T1C())();
      (rowDefinition2.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "3*"))['MemberwiseClone']());
      var rowDefinition3 = new ($T1C())();
      (rowDefinition3.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2*"))['MemberwiseClone']());
      (grid2['get_RowDefinitions']())['Add'](rowDefinition);
      (grid2['get_RowDefinitions']())['Add'](rowDefinition2);
      (grid2['get_RowDefinitions']())['Add'](rowDefinition3);
      var border = new ($T1F())();
      border['set_BorderBrush']($T20().$Cast($T1B()['ConvertFromInvariantString']($T20().__Type__, "Black")));
      (border.BorderThickness = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "0.5"))['MemberwiseClone']());
      border['set_VerticalAlignment']($T23().Bottom);
      var border2 = new ($T1F())();
      $T17()['SetRow'](border2, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      border2['set_BorderBrush']($T20().$Cast($T1B()['ConvertFromInvariantString']($T20().__Type__, "Black")));
      (border2.BorderThickness = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "0.5"))['MemberwiseClone']());
      border2['set_VerticalAlignment']($T23().Bottom);
      var textBlock = new ($T24())();
      textBlock['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "20")));
      (textBlock.FontWeight = $T25().$Cast($T1B()['ConvertFromInvariantString']($T25().__Type__, "DemiBold"))['MemberwiseClone']());
      (textBlock.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10"))['MemberwiseClone']());
      textBlock['set_Text']("\ubaa9\ud45c \ub808\ubca8\uc744 \uae30\uc900\uc73c\ub85c \uc2dc\ub098\ub9ac\uc624 \uc2dc\uc791\uc704\uce58 \ubc0f \uc77c\uae30 \uc694\uad6c\ub7c9 \uacc4\uc0b0");
      var grid3 = new ($T17())();
      $T17()['SetRow'](grid3, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var rowDefinition4 = new ($T1C())();
      (rowDefinition4.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition5 = new ($T1C())();
      (rowDefinition5.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition6 = new ($T1C())();
      (rowDefinition6.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      (grid3['get_RowDefinitions']())['Add'](rowDefinition4);
      (grid3['get_RowDefinitions']())['Add'](rowDefinition5);
      (grid3['get_RowDefinitions']())['Add'](rowDefinition6);
      var columnDefinition = new ($T26())();
      (columnDefinition.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition2 = new ($T26())();
      (columnDefinition2.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2.5*"))['MemberwiseClone']());
      (grid3['get_ColumnDefinitions']())['Add'](columnDefinition);
      (grid3['get_ColumnDefinitions']())['Add'](columnDefinition2);
      var textBlock2 = new ($T24())();
      textBlock2['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock2.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,25,10,10"))['MemberwiseClone']());
      $T17()['SetRow'](textBlock2, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "0")));
      textBlock2['set_Text']("\uba54\uc778 \uc2dc\ub098\ub9ac\uc624 \uc885\ucc29\uc810");
      var textBlock3 = new ($T24())();
      textBlock3['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock3.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10"))['MemberwiseClone']());
      textBlock3['set_VerticalAlignment']($T23().Center);
      $T17()['SetRow'](textBlock3, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      textBlock3['set_Text']("\uc2dc\uc791 \ub808\ubca8");
      var textBlock4 = new ($T24())();
      textBlock4['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock4.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,10,25"))['MemberwiseClone']());
      $T17()['SetRow'](textBlock4, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      textBlock4['set_Text']("\ubaa9\ud45c \ub808\ubca8");
      var comboBox = new ($T28())();
      $T29().prototype['RegisterName'].call(this, "ADestMqBox", comboBox);
      comboBox['set_Name']("ADestMqBox");
      comboBox['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "11")));
      (comboBox.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,25,50,10"))['MemberwiseClone']());
      comboBox['set_DisplayMemberPath']("Option");
      comboBox['set_SelectedValuePath']("Value");
      $T17()['SetColumn'](comboBox, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var binding = $S08().Construct();
      binding['set_Path']($T2C().$Cast($T1B()['ConvertFromInvariantString']($T2C().__Type__, "Items")));
      var grid4 = new ($T17())();
      $T17()['SetRow'](grid4, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      $T17()['SetColumn'](grid4, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var columnDefinition3 = new ($T26())();
      (columnDefinition3.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition4 = new ($T26())();
      (columnDefinition4.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition5 = new ($T26())();
      (columnDefinition5.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      (grid4['get_ColumnDefinitions']())['Add'](columnDefinition3);
      (grid4['get_ColumnDefinitions']())['Add'](columnDefinition4);
      (grid4['get_ColumnDefinitions']())['Add'](columnDefinition5);
      var textBox = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "AStartLevel", textBox);
      textBox['set_Name']("AStartLevel");
      textBox['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,10,10,10"))['MemberwiseClone']());
      textBox['set_VerticalAlignment']($T23().Center);
      var textBlock5 = new ($T24())();
      $T17()['SetColumn'](textBlock5, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      textBlock5['set_VerticalAlignment']($T23().Center);
      textBlock5['set_HorizontalAlignment']($T2D().Center);
      textBlock5['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      textBlock5['set_Text']("\uacbd\ud5d8\uce58%");
      var textBox2 = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "AStartLVval", textBox2);
      textBox2['set_Name']("AStartLVval");
      $T17()['SetColumn'](textBox2, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      textBox2['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox2.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,50,10"))['MemberwiseClone']());
      textBox2['set_VerticalAlignment']($T23().Center);
      (grid4['get_Children']())['Add'](textBox);
      (grid4['get_Children']())['Add'](textBlock5);
      (grid4['get_Children']())['Add'](textBox2);
      var grid5 = new ($T17())();
      $T17()['SetRow'](grid5, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      $T17()['SetColumn'](grid5, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var columnDefinition6 = new ($T26())();
      (columnDefinition6.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition7 = new ($T26())();
      (columnDefinition7.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition8 = new ($T26())();
      (columnDefinition8.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      (grid5['get_ColumnDefinitions']())['Add'](columnDefinition6);
      (grid5['get_ColumnDefinitions']())['Add'](columnDefinition7);
      (grid5['get_ColumnDefinitions']())['Add'](columnDefinition8);
      var textBox3 = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "ADestLevel", textBox3);
      textBox3['set_Name']("ADestLevel");
      textBox3['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox3.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,10,10,25"))['MemberwiseClone']());
      textBox3['set_VerticalAlignment']($T23().Center);
      var textBlock6 = new ($T24())();
      $T17()['SetColumn'](textBlock6, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      (textBlock6.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,10,25"))['MemberwiseClone']());
      textBlock6['set_VerticalAlignment']($T23().Center);
      textBlock6['set_HorizontalAlignment']($T2D().Center);
      textBlock6['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      textBlock6['set_Text']("\uacbd\ud5d8\uce58%");
      var textBox4 = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "ADestLVval", textBox4);
      textBox4['set_Name']("ADestLVval");
      $T17()['SetColumn'](textBox4, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      textBox4['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox4.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,50,25"))['MemberwiseClone']());
      textBox4['set_VerticalAlignment']($T23().Center);
      (grid5['get_Children']())['Add'](textBox3);
      (grid5['get_Children']())['Add'](textBlock6);
      (grid5['get_Children']())['Add'](textBox4);
      (grid3['get_Children']())['Add'](textBlock2);
      (grid3['get_Children']())['Add'](textBlock3);
      (grid3['get_Children']())['Add'](textBlock4);
      (grid3['get_Children']())['Add'](comboBox);
      (grid3['get_Children']())['Add'](grid4);
      (grid3['get_Children']())['Add'](grid5);
      var grid6 = new ($T17())();
      $T17()['SetRow'](grid6, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      var columnDefinition9 = new ($T26())();
      (columnDefinition9.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "0.5*"))['MemberwiseClone']());
      var columnDefinition10 = new ($T26())();
      (columnDefinition10.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "0.5*"))['MemberwiseClone']());
      var columnDefinition11 = new ($T26())();
      (columnDefinition11.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2*"))['MemberwiseClone']());
      (grid6['get_ColumnDefinitions']())['Add'](columnDefinition9);
      (grid6['get_ColumnDefinitions']())['Add'](columnDefinition10);
      (grid6['get_ColumnDefinitions']())['Add'](columnDefinition11);
      var button = new ($T30())();
      button['add_Click']($T32()['New'](this, $thisType.prototype['AConfirm'], function () { return JSIL.GetMethodInfo($thisType, "AConfirm", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      (button.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "20"))['MemberwiseClone']());
      button['set_Content']($T1B()['ConvertFromInvariantString']($T0D().__Type__, "\uacc4\uc0b0\ud558\uae30"));
      var textBlock7 = new ($T24())();
      (textBlock7.FontWeight = $T25().$Cast($T1B()['ConvertFromInvariantString']($T25().__Type__, "ExtraBold"))['MemberwiseClone']());
      textBlock7['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "30")));
      $T17()['SetColumn'](textBlock7, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      textBlock7['set_HorizontalAlignment']($T2D().Center);
      textBlock7['set_VerticalAlignment']($T23().Center);
      textBlock7['set_Text']("=>");
      var label = new ($T33())();
      $T29().prototype['RegisterName'].call(this, "AResultWindow", label);
      label['set_Name']("AResultWindow");
      $T17()['SetColumn'](label, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      label['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      label['set_HorizontalAlignment']($T2D().Center);
      label['set_VerticalAlignment']($T23().Center);
      (grid6['get_Children']())['Add'](button);
      (grid6['get_Children']())['Add'](textBlock7);
      (grid6['get_Children']())['Add'](label);
      (grid2['get_Children']())['Add'](border);
      (grid2['get_Children']())['Add'](border2);
      (grid2['get_Children']())['Add'](textBlock);
      (grid2['get_Children']())['Add'](grid3);
      (grid2['get_Children']())['Add'](grid6);
      tabItem['set_Content'](grid2);
      var tabItem2 = new ($T19())();
      tabItem2['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "13")));
      tabItem2['set_Header']($T1B()['ConvertFromInvariantString']($T0D().__Type__, "\ub3c4\ub2ec \ub808\ubca8 \uacc4\uc0b0"));
      var grid7 = new ($T17())();
      var rowDefinition7 = new ($T1C())();
      (rowDefinition7.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition8 = new ($T1C())();
      (rowDefinition8.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "3*"))['MemberwiseClone']());
      var rowDefinition9 = new ($T1C())();
      (rowDefinition9.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2*"))['MemberwiseClone']());
      (grid7['get_RowDefinitions']())['Add'](rowDefinition7);
      (grid7['get_RowDefinitions']())['Add'](rowDefinition8);
      (grid7['get_RowDefinitions']())['Add'](rowDefinition9);
      var border3 = new ($T1F())();
      border3['set_BorderBrush']($T20().$Cast($T1B()['ConvertFromInvariantString']($T20().__Type__, "Black")));
      (border3.BorderThickness = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "0.5"))['MemberwiseClone']());
      border3['set_VerticalAlignment']($T23().Bottom);
      var border4 = new ($T1F())();
      $T17()['SetRow'](border4, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      border4['set_BorderBrush']($T20().$Cast($T1B()['ConvertFromInvariantString']($T20().__Type__, "Black")));
      (border4.BorderThickness = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "0.5"))['MemberwiseClone']());
      border4['set_VerticalAlignment']($T23().Bottom);
      var textBlock8 = new ($T24())();
      textBlock8['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "20")));
      (textBlock8.FontWeight = $T25().$Cast($T1B()['ConvertFromInvariantString']($T25().__Type__, "DemiBold"))['MemberwiseClone']());
      (textBlock8.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10"))['MemberwiseClone']());
      textBlock8['set_Text']("\uba54\uc778 \uc2dc\ub098\ub9ac\uc624 \ubc94\uc704\ub97c \uae30\uc900\uc73c\ub85c \uc608\uc0c1 \ub3c4\ub2ec\ub808\ubca8 \uacc4\uc0b0");
      var grid8 = new ($T17())();
      $T17()['SetRow'](grid8, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var rowDefinition10 = new ($T1C())();
      (rowDefinition10.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition11 = new ($T1C())();
      (rowDefinition11.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition12 = new ($T1C())();
      (rowDefinition12.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      (grid8['get_RowDefinitions']())['Add'](rowDefinition10);
      (grid8['get_RowDefinitions']())['Add'](rowDefinition11);
      (grid8['get_RowDefinitions']())['Add'](rowDefinition12);
      var columnDefinition12 = new ($T26())();
      (columnDefinition12.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition13 = new ($T26())();
      (columnDefinition13.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2.5*"))['MemberwiseClone']());
      (grid8['get_ColumnDefinitions']())['Add'](columnDefinition12);
      (grid8['get_ColumnDefinitions']())['Add'](columnDefinition13);
      var textBlock9 = new ($T24())();
      textBlock9['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock9.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,25,10,10"))['MemberwiseClone']());
      $T17()['SetRow'](textBlock9, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "0")));
      textBlock9['set_Text']("\uba54\uc778 \uc2dc\ub098\ub9ac\uc624 \uc2dc\uc791\uc810");
      var textBlock10 = new ($T24())();
      textBlock10['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock10.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10"))['MemberwiseClone']());
      textBlock10['set_VerticalAlignment']($T23().Center);
      $T17()['SetRow'](textBlock10, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      textBlock10['set_Text']("\uba54\uc778 \uc2dc\ub098\ub9ac\uc624 \uc885\ucc29\uc810");
      var textBlock11 = new ($T24())();
      textBlock11['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock11.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,10,25"))['MemberwiseClone']());
      $T17()['SetRow'](textBlock11, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      textBlock11['set_Text']("\uc2dc\uc791 \ub808\ubca8");
      var comboBox2 = new ($T28())();
      $T29().prototype['RegisterName'].call(this, "BStartMqBox", comboBox2);
      comboBox2['set_Name']("BStartMqBox");
      comboBox2['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "11")));
      (comboBox2.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,25,50,10"))['MemberwiseClone']());
      comboBox2['set_DisplayMemberPath']("Option");
      comboBox2['set_SelectedValuePath']("Value");
      $T17()['SetColumn'](comboBox2, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var binding2 = $S08().Construct();
      binding2['set_Path']($T2C().$Cast($T1B()['ConvertFromInvariantString']($T2C().__Type__, "Items")));
      var comboBox3 = new ($T28())();
      $T29().prototype['RegisterName'].call(this, "BDestMqBox", comboBox3);
      comboBox3['set_Name']("BDestMqBox");
      comboBox3['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "11")));
      (comboBox3.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,17.5,50,17.5"))['MemberwiseClone']());
      comboBox3['set_DisplayMemberPath']("Option");
      comboBox3['set_SelectedValuePath']("Value");
      $T17()['SetColumn'](comboBox3, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      $T17()['SetRow'](comboBox3, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var binding3 = $S08().Construct();
      binding3['set_Path']($T2C().$Cast($T1B()['ConvertFromInvariantString']($T2C().__Type__, "Items")));
      var grid9 = new ($T17())();
      $T17()['SetRow'](grid9, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      $T17()['SetColumn'](grid9, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var columnDefinition14 = new ($T26())();
      (columnDefinition14.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition15 = new ($T26())();
      (columnDefinition15.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition16 = new ($T26())();
      (columnDefinition16.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      (grid9['get_ColumnDefinitions']())['Add'](columnDefinition14);
      (grid9['get_ColumnDefinitions']())['Add'](columnDefinition15);
      (grid9['get_ColumnDefinitions']())['Add'](columnDefinition16);
      var textBox5 = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "BStartLevel", textBox5);
      textBox5['set_Name']("BStartLevel");
      textBox5['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox5.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,10,10,25"))['MemberwiseClone']());
      textBox5['set_VerticalAlignment']($T23().Center);
      var textBlock12 = new ($T24())();
      $T17()['SetColumn'](textBlock12, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      (textBlock12.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,10,25"))['MemberwiseClone']());
      textBlock12['set_VerticalAlignment']($T23().Center);
      textBlock12['set_HorizontalAlignment']($T2D().Center);
      textBlock12['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      textBlock12['set_Text']("\uacbd\ud5d8\uce58%");
      var textBox6 = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "BStartLVval", textBox6);
      textBox6['set_Name']("BStartLVval");
      $T17()['SetColumn'](textBox6, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      textBox6['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox6.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,50,25"))['MemberwiseClone']());
      textBox6['set_VerticalAlignment']($T23().Center);
      (grid9['get_Children']())['Add'](textBox5);
      (grid9['get_Children']())['Add'](textBlock12);
      (grid9['get_Children']())['Add'](textBox6);
      (grid8['get_Children']())['Add'](textBlock9);
      (grid8['get_Children']())['Add'](textBlock10);
      (grid8['get_Children']())['Add'](textBlock11);
      (grid8['get_Children']())['Add'](comboBox2);
      (grid8['get_Children']())['Add'](comboBox3);
      (grid8['get_Children']())['Add'](grid9);
      var grid10 = new ($T17())();
      $T17()['SetRow'](grid10, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      var columnDefinition17 = new ($T26())();
      (columnDefinition17.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "0.5*"))['MemberwiseClone']());
      var columnDefinition18 = new ($T26())();
      (columnDefinition18.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "0.5*"))['MemberwiseClone']());
      var columnDefinition19 = new ($T26())();
      (columnDefinition19.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2*"))['MemberwiseClone']());
      (grid10['get_ColumnDefinitions']())['Add'](columnDefinition17);
      (grid10['get_ColumnDefinitions']())['Add'](columnDefinition18);
      (grid10['get_ColumnDefinitions']())['Add'](columnDefinition19);
      var button2 = new ($T30())();
      button2['add_Click']($T32()['New'](this, $thisType.prototype['BConfirm'], function () { return JSIL.GetMethodInfo($thisType, "BConfirm", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      (button2.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "20"))['MemberwiseClone']());
      button2['set_Content']($T1B()['ConvertFromInvariantString']($T0D().__Type__, "\uacc4\uc0b0\ud558\uae30"));
      var textBlock13 = new ($T24())();
      (textBlock13.FontWeight = $T25().$Cast($T1B()['ConvertFromInvariantString']($T25().__Type__, "ExtraBold"))['MemberwiseClone']());
      textBlock13['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "30")));
      $T17()['SetColumn'](textBlock13, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      textBlock13['set_HorizontalAlignment']($T2D().Center);
      textBlock13['set_VerticalAlignment']($T23().Center);
      textBlock13['set_Text']("=>");
      var label2 = new ($T33())();
      $T29().prototype['RegisterName'].call(this, "BResultWindow", label2);
      label2['set_Name']("BResultWindow");
      $T17()['SetColumn'](label2, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      label2['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      label2['set_HorizontalAlignment']($T2D().Center);
      label2['set_VerticalAlignment']($T23().Center);
      (grid10['get_Children']())['Add'](button2);
      (grid10['get_Children']())['Add'](textBlock13);
      (grid10['get_Children']())['Add'](label2);
      (grid7['get_Children']())['Add'](border3);
      (grid7['get_Children']())['Add'](border4);
      (grid7['get_Children']())['Add'](textBlock8);
      (grid7['get_Children']())['Add'](grid8);
      (grid7['get_Children']())['Add'](grid10);
      tabItem2['set_Content'](grid7);
      var tabItem3 = new ($T19())();
      tabItem3['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "13")));
      tabItem3['set_Header']($T1B()['ConvertFromInvariantString']($T0D().__Type__, "\uc2dc\uc791 \ub808\ubca8 \uacc4\uc0b0"));
      var grid11 = new ($T17())();
      var rowDefinition13 = new ($T1C())();
      (rowDefinition13.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition14 = new ($T1C())();
      (rowDefinition14.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "3*"))['MemberwiseClone']());
      var rowDefinition15 = new ($T1C())();
      (rowDefinition15.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2*"))['MemberwiseClone']());
      (grid11['get_RowDefinitions']())['Add'](rowDefinition13);
      (grid11['get_RowDefinitions']())['Add'](rowDefinition14);
      (grid11['get_RowDefinitions']())['Add'](rowDefinition15);
      var border5 = new ($T1F())();
      border5['set_BorderBrush']($T20().$Cast($T1B()['ConvertFromInvariantString']($T20().__Type__, "Black")));
      (border5.BorderThickness = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "0.5"))['MemberwiseClone']());
      border5['set_VerticalAlignment']($T23().Bottom);
      var border6 = new ($T1F())();
      $T17()['SetRow'](border6, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      border6['set_BorderBrush']($T20().$Cast($T1B()['ConvertFromInvariantString']($T20().__Type__, "Black")));
      (border6.BorderThickness = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "0.5"))['MemberwiseClone']());
      border6['set_VerticalAlignment']($T23().Bottom);
      var textBlock14 = new ($T24())();
      textBlock14['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "20")));
      (textBlock14.FontWeight = $T25().$Cast($T1B()['ConvertFromInvariantString']($T25().__Type__, "DemiBold"))['MemberwiseClone']());
      (textBlock14.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10"))['MemberwiseClone']());
      textBlock14['set_Text']("\uba54\uc778 \uc2dc\ub098\ub9ac\uc624 \ubc94\uc704 \ubc0f \ubaa9\ud45c \ub808\ubca8\uc744 \uae30\uc900\uc73c\ub85c \uc2dc\uc791 \ub808\ubca8 \uacc4\uc0b0");
      var grid12 = new ($T17())();
      $T17()['SetRow'](grid12, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var rowDefinition16 = new ($T1C())();
      (rowDefinition16.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition17 = new ($T1C())();
      (rowDefinition17.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var rowDefinition18 = new ($T1C())();
      (rowDefinition18.Height = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      (grid12['get_RowDefinitions']())['Add'](rowDefinition16);
      (grid12['get_RowDefinitions']())['Add'](rowDefinition17);
      (grid12['get_RowDefinitions']())['Add'](rowDefinition18);
      var columnDefinition20 = new ($T26())();
      (columnDefinition20.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition21 = new ($T26())();
      (columnDefinition21.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2.5*"))['MemberwiseClone']());
      (grid12['get_ColumnDefinitions']())['Add'](columnDefinition20);
      (grid12['get_ColumnDefinitions']())['Add'](columnDefinition21);
      var textBlock15 = new ($T24())();
      textBlock15['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock15.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,25,10,10"))['MemberwiseClone']());
      $T17()['SetRow'](textBlock15, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "0")));
      textBlock15['set_Text']("\uba54\uc778 \uc2dc\ub098\ub9ac\uc624 \uc2dc\uc791\uc810");
      var textBlock16 = new ($T24())();
      textBlock16['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock16.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10"))['MemberwiseClone']());
      textBlock16['set_VerticalAlignment']($T23().Center);
      $T17()['SetRow'](textBlock16, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      textBlock16['set_Text']("\uba54\uc778 \uc2dc\ub098\ub9ac\uc624 \uc885\ucc29\uc810");
      var textBlock17 = new ($T24())();
      textBlock17['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBlock17.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,10,25"))['MemberwiseClone']());
      $T17()['SetRow'](textBlock17, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      textBlock17['set_Text']("\ubaa9\ud45c \ub808\ubca8");
      var comboBox4 = new ($T28())();
      $T29().prototype['RegisterName'].call(this, "CStartMqBox", comboBox4);
      comboBox4['set_Name']("CStartMqBox");
      comboBox4['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "11")));
      (comboBox4.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,25,50,10"))['MemberwiseClone']());
      comboBox4['set_DisplayMemberPath']("Option");
      comboBox4['set_SelectedValuePath']("Value");
      $T17()['SetColumn'](comboBox4, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var binding4 = $S08().Construct();
      binding4['set_Path']($T2C().$Cast($T1B()['ConvertFromInvariantString']($T2C().__Type__, "Items")));
      var comboBox5 = new ($T28())();
      $T29().prototype['RegisterName'].call(this, "CDestMqBox", comboBox5);
      comboBox5['set_Name']("CDestMqBox");
      comboBox5['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "11")));
      (comboBox5.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,17.5,50,17.5"))['MemberwiseClone']());
      comboBox5['set_DisplayMemberPath']("Option");
      comboBox5['set_SelectedValuePath']("Value");
      $T17()['SetColumn'](comboBox5, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      $T17()['SetRow'](comboBox5, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var binding5 = $S08().Construct();
      binding5['set_Path']($T2C().$Cast($T1B()['ConvertFromInvariantString']($T2C().__Type__, "Items")));
      var grid13 = new ($T17())();
      $T17()['SetRow'](grid13, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      $T17()['SetColumn'](grid13, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      var columnDefinition22 = new ($T26())();
      (columnDefinition22.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition23 = new ($T26())();
      (columnDefinition23.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      var columnDefinition24 = new ($T26())();
      (columnDefinition24.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "*"))['MemberwiseClone']());
      (grid13['get_ColumnDefinitions']())['Add'](columnDefinition22);
      (grid13['get_ColumnDefinitions']())['Add'](columnDefinition23);
      (grid13['get_ColumnDefinitions']())['Add'](columnDefinition24);
      var textBox7 = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "CDestLevel", textBox7);
      textBox7['set_Name']("CDestLevel");
      textBox7['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox7.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "50,10,10,25"))['MemberwiseClone']());
      textBox7['set_VerticalAlignment']($T23().Center);
      var textBlock18 = new ($T24())();
      $T17()['SetColumn'](textBlock18, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      (textBlock18.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,10,25"))['MemberwiseClone']());
      textBlock18['set_VerticalAlignment']($T23().Center);
      textBlock18['set_HorizontalAlignment']($T2D().Center);
      textBlock18['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      textBlock18['set_Text']("\uacbd\ud5d8\uce58%");
      var textBox8 = new ($T0C())();
      $T29().prototype['RegisterName'].call(this, "CDestLVval", textBox8);
      textBox8['set_Name']("CDestLVval");
      $T17()['SetColumn'](textBox8, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      textBox8['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      (textBox8.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "10,10,50,25"))['MemberwiseClone']());
      textBox8['set_VerticalAlignment']($T23().Center);
      (grid13['get_Children']())['Add'](textBox7);
      (grid13['get_Children']())['Add'](textBlock18);
      (grid13['get_Children']())['Add'](textBox8);
      (grid12['get_Children']())['Add'](textBlock15);
      (grid12['get_Children']())['Add'](textBlock16);
      (grid12['get_Children']())['Add'](textBlock17);
      (grid12['get_Children']())['Add'](comboBox4);
      (grid12['get_Children']())['Add'](comboBox5);
      (grid12['get_Children']())['Add'](grid13);
      var grid14 = new ($T17())();
      $T17()['SetRow'](grid14, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      var columnDefinition25 = new ($T26())();
      (columnDefinition25.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "0.5*"))['MemberwiseClone']());
      var columnDefinition26 = new ($T26())();
      (columnDefinition26.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "0.5*"))['MemberwiseClone']());
      var columnDefinition27 = new ($T26())();
      (columnDefinition27.Width = $T1D().$Cast($T1B()['ConvertFromInvariantString']($T1D().__Type__, "2*"))['MemberwiseClone']());
      (grid14['get_ColumnDefinitions']())['Add'](columnDefinition25);
      (grid14['get_ColumnDefinitions']())['Add'](columnDefinition26);
      (grid14['get_ColumnDefinitions']())['Add'](columnDefinition27);
      var button3 = new ($T30())();
      button3['add_Click']($T32()['New'](this, $thisType.prototype['CConfirm'], function () { return JSIL.GetMethodInfo($thisType, "CConfirm", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      (button3.Margin = $T21().$Cast($T1B()['ConvertFromInvariantString']($T21().__Type__, "20"))['MemberwiseClone']());
      button3['set_Content']($T1B()['ConvertFromInvariantString']($T0D().__Type__, "\uacc4\uc0b0\ud558\uae30"));
      var textBlock19 = new ($T24())();
      (textBlock19.FontWeight = $T25().$Cast($T1B()['ConvertFromInvariantString']($T25().__Type__, "ExtraBold"))['MemberwiseClone']());
      textBlock19['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "30")));
      $T17()['SetColumn'](textBlock19, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "1")));
      textBlock19['set_HorizontalAlignment']($T2D().Center);
      textBlock19['set_VerticalAlignment']($T23().Center);
      textBlock19['set_Text']("=>");
      var label3 = new ($T33())();
      $T29().prototype['RegisterName'].call(this, "CResultWindow", label3);
      label3['set_Name']("CResultWindow");
      $T17()['SetColumn'](label3, $T06().$Cast($T1B()['ConvertFromInvariantString']($T06().__Type__, "2")));
      label3['set_FontSize']($T12().$Cast($T1B()['ConvertFromInvariantString']($T12().__Type__, "15")));
      label3['set_HorizontalAlignment']($T2D().Center);
      label3['set_VerticalAlignment']($T23().Center);
      (grid14['get_Children']())['Add'](button3);
      (grid14['get_Children']())['Add'](textBlock19);
      (grid14['get_Children']())['Add'](label3);
      (grid11['get_Children']())['Add'](border5);
      (grid11['get_Children']())['Add'](border6);
      (grid11['get_Children']())['Add'](textBlock14);
      (grid11['get_Children']())['Add'](grid12);
      (grid11['get_Children']())['Add'](grid14);
      tabItem3['set_Content'](grid11);
      (tabControl['get_Items']())['Add'](tabItem);
      (tabControl['get_Items']())['Add'](tabItem2);
      (tabControl['get_Items']())['Add'](tabItem3);
      (grid['get_Children']())['Add'](tabControl);
      this['set_Content'](grid);
      var binding6 = $S08().Construct();
      var relativeSource = $S09().Construct();
      relativeSource['set_Mode']($T36().Self);
      binding6['set_RelativeSource'](relativeSource);
      this.ADestMqBox = comboBox;
      this.AStartLevel = textBox;
      this.AStartLVval = textBox2;
      this.ADestLevel = textBox3;
      this.ADestLVval = textBox4;
      this.AResultWindow = label;
      this.BStartMqBox = comboBox2;
      this.BDestMqBox = comboBox3;
      this.BStartLevel = textBox5;
      this.BStartLVval = textBox6;
      this.BResultWindow = label2;
      this.CStartMqBox = comboBox4;
      this.CDestMqBox = comboBox5;
      this.CDestLevel = textBox7;
      this.CDestLVval = textBox8;
      this.CResultWindow = label3;
      comboBox['SetBinding']($T2A().ItemsSourceProperty, binding);
      comboBox2['SetBinding']($T2A().ItemsSourceProperty, binding2);
      comboBox3['SetBinding']($T2A().ItemsSourceProperty, binding3);
      comboBox4['SetBinding']($T2A().ItemsSourceProperty, binding4);
      comboBox5['SetBinding']($T2A().ItemsSourceProperty, binding5);
      this['SetBinding']($T22().DataContextProperty, binding6);
    }
  };

  JSIL.MakeType({
      BaseType: $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Page"), 
      Name: "Application1.MainPage", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MainPage__ctor
    );

    $.Method({Static:false, Public:false}, "AConfirm", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_AConfirm
    );

    $.Method({Static:false, Public:false}, "BConfirm", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_BConfirm
    );

    $.Method({Static:false, Public:false}, "CConfirm", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_CConfirm
    );

    $.Method({Static:false, Public:false}, "CutString", 
      new JSIL.MethodSignature($.String, [
          $.String, $.String, 
          $.String
        ]), 
      MainPage_CutString
    );

    $.Method({Static:false, Public:true }, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      MainPage_InitializeComponent
    );

    $['Field']({Static:false, Public:true }, "Items", $asm_mscorlib.TypeRef("System.Collections.Generic.List`1", [$asm_Application1.TypeRef("Application1.CItem")])); 
    $['Field']({Static:false, Public:false}, "ADestMqBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "AStartLevel", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "AStartLVval", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "ADestLevel", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "ADestLVval", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "AResultWindow", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Label")); 
    $['Field']({Static:false, Public:false}, "BStartMqBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "BDestMqBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "BStartLevel", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "BStartLVval", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "BResultWindow", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Label")); 
    $['Field']({Static:false, Public:false}, "CStartMqBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "CDestMqBox", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.ComboBox")); 
    $['Field']({Static:false, Public:false}, "CDestLevel", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "CDestLVval", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.TextBox")); 
    $['Field']({Static:false, Public:false}, "CResultWindow", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Label")); 
    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

